### ISSUE TITLE
Transaction issue

### ISSUE THREAD

**Issue by inx-priyank** [AhsanAyaz/flutter_stripe_payments#5]
When I make the transaction, I get the response as 
"As per Indian regulations, export transactions require a customer name and address. More info here: https://stripe.com/docs/india-exports" in platform exception block. Please suggest how to pass the customer name and address.

**Comment by AhsanAyaz** [comment]
@InheritxSolution you can use the below function for that. Just replace the code in [PaymentService.dart](https://github.com/AhsanAyaz/flutter_stripe_payments/blob/master/lib/services/payment-service.dart):

```dart
static Future<Map<String, dynamic>> createPaymentIntent(String amount, String currency, String name, String shippingAddress, String description) async {
    try {
      Map<String, dynamic> body = {
        'amount': amount,
        'currency': currency,
        'payment_method_types[]': 'card',
        'shipping[name]': name,
        'description': description,
        'shipping[address][line1]'='510 Townsend St'
        'shipping[address][postal_code]'=98140 \
        'shipping[address][city]'='San Francisco'
        'shipping[address][state]'='CA'
        'shipping[address][country]'='US'
      };
      var response = await http.post(
        StripeService.paymentApiUrl,
        body: body,
        headers: StripeService.headers
      );
      return jsonDecode(response.body);
    } catch (err) {
      print('err charging user: ${err.toString()}');
    }
    return null;
  }
```

**Comment by AhsanAyaz** [comment]
@InheritxSolution I'm closing the issue. Feel free to re-open if you still face issue 🙂

**Comment by manpreetkaur-1403** [comment]
I am using this but getting same error Expected an Identifier in address ,rest parameters are working fine

**Comment by AhsanAyaz** [comment]
@manpreetkaur-1403 could you share the error here?

**Comment by manpreetkaur-1403** [comment]
The error was due to syntax for hashmap in flutter. Now I am trying to implement existing card payment method and get following error . Please review this and help me for doing payment with existing card

E/MethodChannel#stripe_payment(18032): Failed to handle method call
E/MethodChannel#stripe_payment(18032): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.stripe.android.Stripe.createPaymentMethod(com.stripe.android.model.PaymentMethodCreateParams, com.stripe.android.ApiResultCallback)' on a null object reference
E/MethodChannel#stripe_payment(18032): 	at com.gettipsi.stripe.StripeModule.createPaymentMethod(StripeModule.java:376)
E/MethodChannel#stripe_payment(18032): 	at de.jonasbark.stripepayment.StripePaymentPlugin.onMethodCall(StripePaymentPlugin.kt:45)
E/MethodChannel#stripe_payment(18032): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#stripe_payment(18032): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#stripe_payment(18032): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#stripe_payment(18032): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#stripe_payment(18032): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#stripe_payment(18032): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#stripe_payment(18032): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#stripe_payment(18032): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#stripe_payment(18032): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#stripe_payment(18032): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
